name: motioncastmedia.com
favicon: null
layout_spectrum: 0.46641210396774113
typography_spectrum: 0.41859521018341184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030303'
    - '#272727'
    - '#585858'
    - '#b7b7b7'
  brandStrength: 0.3125
  lightness: 0.963347140699625
  saturation: 0.002146094338968396
  rhythmicContrast: 0.781276039313525
purpose: []
